apiVersion: v1
kind: Service
metadata:
  name: {{ include "exasense.fullname" . }}-api
  namespace: {{ include "exasense.namespace" . }}
  labels:
    {{- include "exasense.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "exasense.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
