apiVersion: v1
kind: Service
metadata:
  name: {{ include "exasense.fullname" . }}-frontend
  namespace: {{ include "exasense.namespace" . }}
  labels:
    {{- include "exasense.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "exasense.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
