apiVersion: v1
kind: Secret
metadata:
  name: {{ include "exasense.fullname" . }}-secrets
  namespace: {{ include "exasense.namespace" . }}
  labels:
    {{- include "exasense.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ required "api.env.JWT_SECRET is required" .Values.api.env.JWT_SECRET | quote }}
  POSTGRES_PASSWORD: {{ required "postgres.auth.password is required" .Values.postgres.auth.password | quote }}
  MINIO_ACCESS_KEY: {{ required "minio.auth.accessKey is required" .Values.minio.auth.accessKey | quote }}
  MINIO_SECRET_KEY: {{ required "minio.auth.secretKey is required" .Values.minio.auth.secretKey | quote }}
